---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldieslocks-main
  labels:
    app: goldieslocks
spec:
  selector:
    matchLabels:
      component: goldieslocks-main
  template:
    metadata:
      labels:
        component: goldieslocks-main
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ghcr.io/sphinxgaia/goldie-main:goldieslocks
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 9000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vault-db-creds-secret
                key: password
        volumeMounts:
            - name: secrets-store-inline
              mountPath: "/secret"
              readOnly: true
    volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vault-master"

---
apiVersion: v1
kind: Service
metadata:
  name: goldieslocks-main
  labels:
    app: goldieslocks
spec:
  selector:
    component: goldieslocks-main
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30032
  # type: ClusterIP
  # change to NodePort if no LoadBalancer controller is available
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldieslocks-body
  labels:
    app: goldieslocks
spec:
  selector:
    matchLabels:
      component: goldieslocks-body
  template:
    metadata:
      labels:
        component: goldieslocks-body
    spec:
      serviceAccountName: goldieslocks
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        # image: busybox
        # command: 
        # - /bin/sh
        # args:
        # - -c
        # - |
        #   sleep 15000
        image:  ghcr.io/sphinxgaia/goldie-body:goldieslocks
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 9000
        env:
          - name: PORT
            value: "9000"
          - name: VERSION
            valueFrom:
              secretKeyRef:
                name: secrets-store-inline
                key: version
        volumeMounts:
            - name: secrets-store-inline
              mountPath: "/secret"
              readOnly: true
    volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vault-master"
---
apiVersion: v1
kind: Service
metadata:
  name: goldieslocks-body
  labels:
    app: goldieslocks
spec:
  selector:
    component: goldieslocks-body
  ports:
    - name: http
      port: 9007
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
