---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldieslocks-main
  labels:
    app: goldieslocks
spec:
  selector:
    matchLabels:
      component: goldieslocks-main
  template:
    metadata:
      labels:
        component: goldieslocks-main
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ghcr.io/sphinxgaia/goldie-main:goldieslocks
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: goldieslocks-main
  labels:
    app: goldieslocks
spec:
  selector:
    component: goldieslocks-main
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30011
  # type: ClusterIP
  # change to NodePort if no LoadBalancer controller is available
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldieslocks-body
  labels:
    app: goldieslocks
spec:
  selector:
    matchLabels:
      component: goldieslocks-body
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/auth-path: auth/midbear
        vault.hashicorp.com/role: midbear        
        vault.hashicorp.com/agent-inject-secret-version: 'midbear/data/soup'
        vault.hashicorp.com/agent-inject-template-version: '{{- with secret "midbear/data/soup" -}}{{ .Data.data.gustative }}{{- end }}'
        vault.hashicorp.com/secret-volume-path-version: "/secret"
      labels:
        component: goldieslocks-body
    spec:
      serviceAccountName: goldieslocks
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          # image: busybox
          # command: 
          # - /bin/sh
          # args:
          # - -c
          # - |
          #   sleep 15000
          image: ghcr.io/sphinxgaia/goldie-body:goldieslocks
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: goldieslocks-body
  labels:
    app: goldieslocks
spec:
  selector:
    component: goldieslocks-body
  ports:
    - name: http
      port: 9007
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
